name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: victor-bern/go_users_mongo # This is the action
        with:
          heroku_api_key: 95bdf3d5-c101-4317-894c-cf90c75dd5ef
          heroku_app_name: "testegolang3" #Must be unique in Heroku
          heroku_email: "victor_santos.15@hotmail.com"
          usedocker: true
