name: Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Heroku Action
        uses: CDNievas/heroku-action@v1.0
        with:
          heroku_api_key: 95bdf3d5-c101-4317-894c-cf90c75dd5ef
          # Email from Heroku Account
          heroku_email: victor_santos.15@hotmail.com
          # The appname to use for deploying/updating
          heroku_app_name: testegolang3
 
