name: Deploy

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Heroku Build
        uses: behe/heroku-build@v1
        with:
          # Name of Heroku application
          app-name: testegolang3
          # API key with the deploy role
          api-key: 95bdf3d5-c101-4317-894c-cf90c75dd5ef
